name: Update Curriculum Changelog

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'docs/curriculum/**'
      - 'docs/pedagogy/**'
      - 'docs/platform/**'

jobs:
  update-changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR information
        id: pr-info
        run: |
          echo "pr_title=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "pr_author=${{ github.event.pull_request.user.login }}" >> $GITHUB_OUTPUT
          echo "pr_url=${{ github.event.pull_request.html_url }}" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        run: |
          DATE=$(date +%Y-%m-%d)
          ENTRY="- [${{ steps.pr-info.outputs.pr_title }}](${{ steps.pr-info.outputs.pr_url }}) by @${{ steps.pr-info.outputs.pr_author }}"

          # Insert new entry under [Unreleased] section
          sed -i "/## \[Unreleased\]/a\\
          \\
          ### Changed\\
          $ENTRY" CHANGELOG.md

      - name: Commit changelog
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add CHANGELOG.md
          git commit -m "docs: update changelog for PR #${{ steps.pr-info.outputs.pr_number }}"
          git push
