name: Bug Report
description: Report a bug or technical issue with curriculum materials or platforms
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees:
  - technical-team

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide detailed information to help us fix it quickly.

  - type: dropdown
    id: bug-category
    attributes:
      label: Bug Category
      description: What type of bug is this?
      options:
        - Documentation error
        - Broken link
        - Code/example error
        - Platform/technical issue
        - Assessment/grading issue
        - Access/permission issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Where did you encounter this bug?
      options:
        - GitHub repository
        - Canvas LMS
        - Coursera
        - Google Cloud Platform
        - Course materials (general)
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where specifically did you find this bug?
      placeholder: e.g., docs/curriculum/deep_learning.md line 45, Canvas Module 3 Quiz 2
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: Clear description of the bug
      placeholder: What's wrong? What did you expect vs. what actually happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: Describe what you expected to see or happen

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe what you actually saw or what actually happened

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Error Messages
      description: If applicable, add screenshots or paste error messages
      placeholder: |
        Paste screenshots or error messages here

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: |
        - OS: [e.g., Windows 10, macOS 13, Ubuntu 22.04]
        - Browser: [e.g., Chrome 119, Firefox 120, Safari 17]
        - Course: [e.g., Introduction to ML, Deep Learning]
        - Date encountered: [e.g., 2025-11-01]

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor issue, workaround available
        - Medium - Affects functionality but not critical
        - High - Blocks learning or major functionality
        - Critical - System down or data loss
      default: 1
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found any workaround for this issue?
      placeholder: If you've found a way to work around this bug, please share

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful?
      placeholder: Add any other context about the problem here

  - type: checkboxes
    id: checklist
    attributes:
      label: Bug Report Checklist
      description: Please confirm
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have provided clear steps to reproduce
          required: true
        - label: I have included relevant environment information
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this bug report, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
